# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=8, null=True)),
                ('Tipo', models.CharField(max_length=10, null=True)),
                ('timestamp2', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
