# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-16 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertas',
            old_name='timestamp2',
            new_name='tiempo',
        ),
        migrations.RenameField(
            model_name='lecturatemphume',
            old_name='timestamp',
            new_name='tiempo',
        ),
    ]
