# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20171216_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='Tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
